# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: "true"
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
pr:
  autoCancel: "true"
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
jobs:
- job: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install sfdx-cli --global
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid 3MVG9pRzvMkjMb6ll1EFC0FaamNMMg9JLYbVW6AzBOLoTyWWCwn0j2A6rPwIhVZylJaIIxg79i6w51F.TKIkQ --jwtkeyfile ./buildfiles/server.key --username NEILS@DEV.COM --instanceurl https://login.salesforce.com -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:convert -r ./force-app -d ./toDeploy
      displayName: Convert to deploy source
    - bash: 
        sfdx force:mdapi:deploy -l RunLocalTests -c -d ./toDeploy -u prod -w 10
      displayName: Run validation on source code
    - bash: 
        sfdx force:mdapi:deploy -l RunLocalTests -d ./toDeploy -u prod -w 10
      displayName: Deploy source code to Production